### ISSUE TITLE
Small addendum for Blender support - Need to enable the material import option

### ISSUE THREAD

**Issue by jessey-git** [erich666/McUsd#2]
Hello, great to see more USD resources coming online.

Right now for Blender materials to be imported at all, you'll need to enable the following option during Import (in the Experimental section):
![blender-import](https://user-images.githubusercontent.com/7989986/187587036-32051dd1-4387-4358-9e5b-aa120f090953.png)

That should hopefully end up with something along the lines of the following for a render:
![ex](https://user-images.githubusercontent.com/7989986/187586832-9dab52ef-d8a3-4a8b-b6e1-6aa0c1f094aa.png)

Do note that there's some known issues around translating the USD PreviewSurface into the Principled BSDF, as is currently done.  But definitely let us know if you run into any further problems over at:
- https://blender.chat/  (channel `pipeline-assets-io-module`)
- https://developer.blender.org/

**Comment by bitinn** [comment]
Side note, a better, much more fully featured usd experimental build of blender can be found here:

https://builder.blender.org/download/experimental/

**Comment by erich666** [comment]
Oh, thanks! I will retest after Labor Day weekend. I hope they’ll make that option default someday.

**Comment by erich666** [comment]
I've tried the latest experimental version and updated the results: https://github.com/erich666/McUsd#blender - nice to see this progress!

**Comment by jessey-git** [comment]
@erich666 Thanks for the update there. However, 2 additional things:
- It's perfectly fine to use the "normal" build of blender for this scene. No need to use the experimental version. The material loading option is the same right now and the features required for this scene are the same in both currently.
- It looks like you used Blender's real-time OpenGL render engine (Eevee) as opposed to the path tracer (Cycles) which is why things like shadows are somewhat bad.

Want another issue for these?
